Amazonneuve/urls.py
from django.contrib import admin
# from django.urls import path
from django.urls import include, path

urlpatterns = [
    path("", include("gestion_vente.urls")),
    path('admin/', admin.site.urls),
]

gestion_vente/urls.py
from django.urls import path
from gestion_vente import views

urlpatterns = [
    path("", views.home, name="home"),
    path("compte/creer/", views.compte_creer, name="compte_creer"),
    path("compte/liste/", views.compte_liste, name="compte_liste"),
    path("compte/login/", views.compte_login, name="compte_login"),
    path("compte/panier/", views.compte_panier, name="compte_panier"),
    path("compte/shopping/", views.shopping, name="shopping"),
    path("compte/deconnecter/", views.compte_deconnecter, name="compte_deconnecter"),
    path("compte/<int:nid>/delete/", views.compte_delete, name="compte_delete"),
    path("compte/commander/", views.compte_commander, name="compte_commander"),
    path("compte/histoire/", views.compte_histoire, name="compte_histoire"),
    path("adresse/creer/", views.adresse_creer, name="adresse_creer"),
    path("adresse/<int:nid>/modifier/", views.adresse_modifier, name="adresse_modifier"),
    path("adresse/<int:nid>/delete/", views.adresse_delete, name="adresse_delete"),
    path("produit/<int:nid>/delete/", views.produit_delete, name="produit_delete"),
    path("produit/<int:nid>/edit/", views.produit_edit, name="produit_edit"),
    path("produit/liste/", views.produit_liste, name="produit_liste"),
    path("panier/liste/", views.liste_ligne_panier, name="liste_ligne_panier"),
    path("inventaire/liste/", views.inventaire_liste, name="inventaire_liste"),
    path("inventaire/<int:nid>/delete/", views.inventaire_delete, name="inventaire_delete"),
    path("linge_panier/<int:nid>/delete/", views.panier_delete, name="panier_delete"),
    path("inventaire/<int:nid>/edit/", views.inventaire_edit, name="inventaire_edit"),
    path("compte/caisse/", views.compte_caisse, name="compte_caisse"),
    path("compte/info/", views.compte_info, name="compte_info"),
    path("compte/modifier/", views.compte_modifer, name="compte__modifer"),
    path("commande/<int:nid>/recommande/", views.recommander, name="recommander"),
    path("recette/", views.recette, name="recette"),
    # path("image/code/", views.image_code, name="image_code"),



]

gestion_vente/models.py
from email.policy import default
from operator import mod
from random import choices
from statistics import mode
from tabnanny import verbose
from django.db import models

class CompteUser(models.Model):

    nomCompte = models.CharField(verbose_name='Nom Compte',max_length=20, unique=True)
    nom = models.CharField(verbose_name='Nom',  max_length=20)
    prenom = models.CharField(verbose_name='Prenom', max_length=20)
    telephone = models.CharField(verbose_name='Telephone', max_length=20)
    courriel = models.EmailField(verbose_name='courriel')
    motDePasse = models.CharField(verbose_name='Mot de passe',  max_length=64)
    dateNaissance = models.DateField(verbose_name='Date de naissance', null=True, blank=True)
    gender_choices = (
        (1, 'Homme'),
        (2, 'Femme'),
    )
    gender = models.SmallIntegerField(verbose_name='Sexe', choices=gender_choices,null=True, blank=True)

    def __str__(self) -> str:
        return self.nomCompte


class Adresse(models.Model):

    Compte = models.ForeignKey(verbose_name='ID compte', to="CompteUser", to_field="id", on_delete=models.CASCADE)
    adresse = models.CharField(verbose_name='adresse', max_length=50)
    ville = models.CharField(verbose_name='ville', max_length=20)
    codePostale = models.CharField(verbose_name='code postale', max_length=7)
    province_choix = [
        ('QC', 'Quebec'),
        ('ON', 'Ontario'),
        ('BC', 'Colombie-Britanique'),
        ('AB', 'Alberta'),
        ('PE', 'Île-du-Prince-Édouard'),
        ('MB', 'Manitoba'),
        ('NB', 'Nouveau-Brunswick'),
        ('NS', 'Nouvelle-Écosse'),
        ('SK', 'Saskatchewan'),
        ('NL', 'Terre-Neuve-et-Labrador'),
        ('NU', 'Nunavut'),
        ('NT', 'Territoires du Nord-Ouest'),
        ('YT', 'Yukon'),
    ]
    province = models.CharField(verbose_name='province', max_length=3, choices=province_choix)

    def __str__(self) -> str:
        return self.adresse + " " + self.ville + " " + self.province + " " + self.codePostale

class Produit(models.Model):

    nomProduit = models.CharField(verbose_name='Nom du Produit', max_length=20)
    typeProduit = models.CharField(verbose_name='type du produit', max_length=20, default="produit")
    prixUnitair = models.DecimalField(verbose_name="Prix Unitaire", max_digits=10, decimal_places=2, default=0)
    lienPhoto = models.CharField(verbose_name='lien photo', max_length=100, default="")

    def __str__(self) -> str:
        return self.nomProduit

class Inventaire(models.Model):

    idProduit = models.ForeignKey(verbose_name="id produit", to="Produit", to_field="id", on_delete=models.CASCADE)
    inventaire = models.IntegerField(verbose_name="quantite",default=0)
    dateLimite = models.DateField(verbose_name="date peremption",default='9999-12-31', null=True, blank=True)
    numLot = models.CharField(verbose_name='numero de lot', max_length=20, null=True, blank=True)


class LignePanier(models.Model):

    nomCompte = models.ForeignKey(verbose_name='id compte',to="CompteUser", to_field="nomCompte",on_delete= models.CASCADE)
    idProduit = models.ForeignKey(verbose_name='id produit',to="Produit", to_field="id",on_delete= models.CASCADE)
    quantite = models.IntegerField(verbose_name="quantite")


class Commande(models.Model):

    nomCompte = models.ForeignKey(verbose_name='id compte',to="CompteUser", to_field="nomCompte",on_delete= models.CASCADE)
    adresseLivre = models.CharField(verbose_name='ville', max_length=100)
    dateCommande = models.DateField(verbose_name='Date de commande', auto_now_add=True)
    montant = models.DecimalField(verbose_name="motant", max_digits=10, decimal_places=2)

class LigneCommande(models.Model):

    idCommande = models.ForeignKey(verbose_name='id commande',to="Commande", to_field="id",on_delete= models.CASCADE)
    produit = models.ForeignKey(verbose_name='produit',to="Produit", to_field="id",on_delete= models.CASCADE)
    prixUnitair = models.DecimalField(verbose_name="Prix Unitaire", max_digits=10, decimal_places=2, default=0)
    quantite = models.IntegerField(verbose_name="quantite")

gestion_vente/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from gestion_vente import models
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from gestion_vente.magasin import Client, Magasin, Order,Panier, ListeRecttes
from gestion_vente.utiles import Pagination, md5
from django.utils.safestring import mark_safe

# forms.ModeForm est la classe prédéfinie Django, on l'hérite pour creer notre propre classe de compteForm
class CompteModelForm(forms.ModelForm):

    nomCompte = forms.CharField(min_length=4, label="Nom Compte")
    telephone = forms.CharField(
        label = "telephone",
    # mettons que numero de telephon au canada est 10 chiffres
        validators = [RegexValidator(r'^\d{10}$', 'telephone invalide')]
    )
    # ajouter un attribut pour confirmer mot de passe
    confirm_mdp = forms.CharField(label="confirmez mot de passe", widget=forms.PasswordInput)
    class Meta:
        model = models.CompteUser
        fields = ["nomCompte", "nom", "prenom", "telephone", "courriel", "motDePasse", "confirm_mdp", "dateNaissance", "gender"]
        widgets = {
            # change input type a password
            "motDePasse": forms.PasswordInput(), 
            "dateNaissance": forms.DateInput(attrs={"type": "date"}),
        }

# verifier si le 'user name' ou telephone ou courriel deja inscrit        
    def clean_telephone(self):
        txt_telephone = self.cleaned_data["telephone"]
        exists = models.CompteUser.objects.filter(telephone=txt_telephone).exists()
        if exists:
            raise ValidationError("Numero de téléphone déjà existant!")

        return txt_telephone

    def clean_nomCompte(self):
        txt_nomCompte = self.cleaned_data["nomCompte"]
        exists = models.CompteUser.objects.filter(nomCompte=txt_nomCompte).exists()
        if exists:
            raise ValidationError("Nom du compte déjà existant!")
        return txt_nomCompte

    def clean_courriel(self):
        txt_courriel = self.cleaned_data["courriel"]
        exists = models.CompteUser.objects.filter(courriel=txt_courriel).exists()
        if exists:
            raise ValidationError("courriel déjà existant!")
        return txt_courriel
 
    def clean_motDePasse(self):
        txt_motDePasse = self.cleaned_data["motDePasse"]
        if len(txt_motDePasse) < 8:
            raise ValidationError("mot de passe doit avoir plus que 8 chars")
        # utiliser md5 pour cacher mot de passe dans la base de donnee
        return md5(txt_motDePasse)

    def clean_confirm_mdp(self):
        txt_motDePasse = self.cleaned_data["motDePasse"]
        txt_confirm_mdp = md5(self.cleaned_data["confirm_mdp"])
        # verifier si les mots de passe sont pareils
        if txt_confirm_mdp != txt_motDePasse:
            raise ValidationError("Mot de passe n'est pas identique! ")
        return txt_confirm_mdp

# on hérite CompteModelForm pour creer CompteModifier. Puis on surcharge les méthodes, pour qu'elles fonctionnent bien pendant qu'on modifie le compte
class CompteModifier(CompteModelForm):

# on doit pas changer nom du compte car il est une cle etrangere dans la base de donnee
    nomCompte = forms.CharField(min_length=4, label="Nom Compte", disabled="disabled")
# si on change pas le numero de telephone, le numero est dans notre base de donnee,
# donc il faut surchareger la methode pour eviter le fausse alarme. Meme concepte pour les attributs suivants
    def clean_telephone(self):
        txt_telephone = self.cleaned_data["telephone"]
        exists = models.CompteUser.objects.exclude(id=self.instance.pk).filter(telephone=txt_telephone).exists()
        if exists:
            raise ValidationError("Numéro de téléphone déjà existant!")
        return txt_telephone
    def clean_nomCompte(self):
        txt_nomCompte = self.cleaned_data["nomCompte"]
        exists = models.CompteUser.objects.exclude(id=self.instance.pk).filter(nomCompte=txt_nomCompte).exists()
        if exists:
            raise ValidationError("Nom du compte déjà existant!")
        return txt_nomCompte
    def clean_courriel(self):
        txt_courriel = self.cleaned_data["courriel"]
        exists = models.CompteUser.objects.exclude(id=self.instance.pk).filter(courriel=txt_courriel).exists()
        if exists:
            raise ValidationError("Courriel déjà existant!")
        return txt_courriel


class AdresseModelForm(forms.ModelForm):
    codePostale = forms.CharField(
        label = "codePostale",
    # code postal doit respecter format canadien
        validators = [RegexValidator('[a-zA-Z][0-9][a-zA-Z][0-9][a-zA-Z][0-9]', 'code postale invalide')]
    )
    class Meta:
        model = models.Adresse
        fields = ('adresse', 'ville', 'codePostale', 'province',)


class produitModelForm(forms.ModelForm):

    class Meta:
        model = models.Produit
        fields = "__all__"


class inventaireModelForm(forms.ModelForm):

    class Meta:
        model = models.Inventaire
        fields = "__all__"

# nav barre change selon le situation de compte connexion
def get_nom():
    nom = '<a href="/compte/login/">se connecter</a></span></li></ul>'
    
    if m.client:
        nom = f'<img src="/static/imgs/connexion.png" alt="">{m.client.compte}</span></li><ul>\
                <li><a href="/compte/info/">profile</a></li><li><a href="/compte/histoire/">mes commandes</a></li>\
                <li><a href="/compte/deconnecter/">déconnection</a></li></ul></ul>'
    nom = mark_safe(nom)
    return nom

def get_nbr():
    nbr = models.LignePanier.objects.filter(nomCompte_id="VISITEUR").count()
    if m.client:
        nbr = models.LignePanier.objects.filter(nomCompte_id=m.client.compte).count()
    return nbr

def home(request):
    nom = get_nom()
    nbr = get_nbr()
    return render(request, "home1.html", {"nom": nom, "nbr": nbr})

def compte_creer(request):

    if request.method == "GET":
        form = CompteModelForm()
        return render(request, "compte_creer.html", {"form":form})

    form = CompteModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        # demander l'utilisateur de creer son adressed des que son compte est cree
        m.login(request.POST.get("nomCompte"))
        return redirect("/adresse/creer/")
    else:
        return render(request, "compte_creer.html", {"form":form})


def compte_modifer(request):
    nom = get_nom()
    nbr = get_nbr()
    if not m.client:
        return redirect("home")
    else:
        row_obj = models.CompteUser.objects.filter(nomCompte=m.client.compte).first()
        if request.method == "GET":
            form = CompteModifier(instance=row_obj)
            return render(request, "compte_modifier.html", {"form": form, "nom": nom, "nbr": nbr})

        form = CompteModifier(data=request.POST, instance=row_obj) 
        if form.is_valid():
            form.save()
            return redirect("/compte/info/")
        else:
            return render(request, "compte_modifier.html", {"form":form, "nom": nom, "nbr": nbr})
        
def adresse_creer(request):
    nom = get_nom()
    nbr = get_nbr()
    if request.method == "GET":
        form = AdresseModelForm()
        return render(request, "adresse_creer.html", {"form": form, "nom": nom, "nbr": nbr})

    form = AdresseModelForm(data=request.POST)
    if form.is_valid():
    # comme AdresseModelForm n'a pas compte_id, il faut "save(commit=False)", puis donner id
        new_adresse = form.save(commit=False)
        new_adresse.Compte_id = models.CompteUser.objects.filter(nomCompte=m.client.compte).first().id
        new_adresse.save()
        return redirect("home")
    else:
        return render(request, "adresse_creer.html", {"form":form, "nom": nom, "nbr": nbr})

def adresse_modifier(request, nid):
    nom = get_nom()
    nbr = get_nbr()
    if not m.client:
        return redirect("home")
    else:
        row_obj = models.Adresse.objects.filter(id=nid).first()
        if request.method == "GET":
            form = AdresseModelForm(instance=row_obj)
            return render(request, "adresse_modifier.html", {"form": form, "nom": nom, "nbr": nbr})

        form = AdresseModelForm(data=request.POST, instance=row_obj) 
        if form.is_valid():
            new_adresse = form.save(commit=False)
            new_adresse.Compte_id = models.CompteUser.objects.filter(nomCompte=m.client.compte).first().id
            new_adresse.save()
            return redirect("/compte/info/")
        else:
            return render(request, "adresse_modifier.html", {"form":form, "nom": nom, "nbr": nbr})

# from gestion_vente.code import check_code
# from io import BytesIO

# def image_code(request):
#     img, code_str = check_code()
#     stream = BytesIO()
#     img.save(stream, 'png')
#     return HttpResponse(stream.getvalue())


def compte_login(request):
    nbr = get_nbr()
    if request.method == "GET":
        return render(request, 'compte_login.html', {"nbr": nbr})
# verifier que le client entre 'user name' ou telephone ou courriel
    data_login = request.POST.get('data_login')
    if models.CompteUser.objects.filter(nomCompte=data_login).exists():
        nom_compte = data_login
    elif models.CompteUser.objects.filter(telephone=data_login).exists():
        nom_compte = models.CompteUser.objects.filter(telephone=data_login).first().nomCompte
    elif models.CompteUser.objects.filter(courriel=data_login).exists():
        nom_compte = models.CompteUser.objects.filter(courriel=data_login).first().nomCompte
    else:
        msg_error = 'Compte n\'existe pas!!'
        return render(request, 'compte_login.html', {"msg_error": msg_error, "nbr": nbr})
    pwd = md5(request.POST.get('pwd')) 
    if pwd == models.CompteUser.objects.filter(nomCompte=nom_compte).first().motDePasse:
# creer objet client par fonction login
        m.login(nom_compte)

gestion_vente/templates/adresse_modifier.html
{% extends "layout.html" %}
{% block title %}
Adresse Modifier
{% endblock %}
{% block content %}
<div class="w compte_creer">
    <fieldset>
        <legend>Créer votre adresse</legend>
    <div>
        <form method="post" novalidate>
            {% csrf_token %}

            {% for field in form %}
            <div >
               <label >{{field.label}}</label>
                {{field}}
                <span style="color: red;">{{field.errors.0}}</span>
              </div>
              {% endfor %} 
              <button type="submit" class="btn">CRÉER</button>
          </form>

    </div>
    </fieldset>
    
</div>
{% endblock %}

gestion_vente/templates/compte_commander.html
{% extends "layout.html" %}
{% block title %}
commander
{% endblock %}
{% block content %}

    <div class="commande_review w">
    <form action="/compte/caisse/" method="post">
        {% csrf_token %}
        <h1><input type="submit" value="Commande Confirmer" id="confirmer" ><span style="color: red;">{{ message }}</span></h1>
    <div class="adresses" style="float: left; margin-left: 0;">
        {% for a in adresses %}
        <div class="adresse">
            <ul>
                <li>{{ a.adresse }}<span style="float: right;"><input type="radio" name="adr_sel" value="{{ a.id }}" required="required"></span></li>
                <li>{{ a.ville }}, {{ a.codePostale }}, {{ a.get_province_display }}</li>
                <button><a href="/adresse/{{ a.id }}/modifier/">Modifier</a></button>
            </ul>
        </div>
        {% endfor %}
        <div class="adresseajouter">
            <button><a href="/adresse/creer/">+</a></button>
        </div>
    </div>

    <div class="commander">
    <table>
    <colgroup>
        <col style="text-align: right">
        <col style="text-align: right">
        <col style="width: 30px; text-align: right">
        <col style="width:30px;text-align: right">
        <col style="width: 50px; font-weight: bold; text-align: right">
      </colgroup>
    <thead>
        <th colspan="2">Produit</th>
        <th>Quantité</th>
        <th>Prix</th>
        <th>Total</th>
    </thead>
    
    <tbody>
    
        {% for line in liste %}
        <tr>
            {% for obj in line %}
            <td>{{ obj }}</td>
            {% endfor %}
        </tr>
        {% endfor %}

       
    </tbody>
    <tfoot>
        <tr>
            
            <th colspan="3" style="text-align: right;">
                Montant Total
            </th>
            <th colspan="2" style="font-size: 20px; font-weight: bold;">
                {{ montant }}$
            </th>
        </tr>
      
    </tfoot>
    
</table>
</div>
    
    
</form>
</div>

{% endblock %}

gestion_vente/templates/compte_creer.html
{% extends "layout.html" %}
{% block title %}
Inscription
{% endblock %}
{% block content %}
<div class="compte_creer w">
    <fieldset>
        <legend>Inscription</legend>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form %}
            <div >
               <label >{{field.label}}</label>
                {{field}}
                <span style="color: red;">{{field.errors.0}}</span>
              </div>
              {% endfor %} 
              <button type="submit" class="btn">Confirmer</button>
          </form>
    </fieldset>
    

</div>
{% endblock %}

gestion_vente/templates/compte_histoire.html
{% extends "layout.html" %}
{% block title %}
Histoire des commandes
{% endblock %}
{% block content %}
<div class="w">

       
    <div class="commandes ">
        {% for commande in commandes %}
        <div class="commande" id="c{{ commande.4 }}">
            <div class="commande_resume">
                <ul>
                    <li>Date commande: {{ commande.0}}</li>
                    <li>Adresse: {{ commande.1 }}</li>
                    <li>Montant total: {{ commande.2 }}$</li>
                </ul>
                <h3><a href="/commande/{{ commande.4 }}/recommande/">Acheter de nouveau</a></h3>
            </div>
            <div class="commande_detail">
                {{ commande.5 }}
                <table style="text-align: right;">
                    <tr>
                        <td>Produit</td>
                        <td>Prix</td>
                        <td>Quantité</td>
                    </tr>
                    <tbody>
                    {% for ligne in commande.3 %}
                    <tr>
                        <td>{{ ligne.produit }}</td>
                        <td>{{ ligne.prixUnitair }}$</td>
                        <td>{{ ligne.quantite }}</td>
                    </tr>
                    {% endfor %}
                    
                    </tbody >
                </table>
                
            </div>
        </div>
        {% endfor %}
       
    </div>
    <ul class="pagination" style="margin-left: 300px;">
        {{ page_string }}
    </ul>
</div>
<script src="/static/js/compte_histoire.js"></script>

{% endblock %}

gestion_vente/templates/compte_liste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste compte</title>
</head>
<body>

    <h1>Liste de compte</h1>
    <div>
        <table>
            {% for user in liste1 %}
            <tr>
                <td>{{ user.nomCompte }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.telephone }} </td>
                <td>{{ user.courriel }}</td>
                <td>{{ user.dateNaissance }}</td>
                <td>{{ user.get_gender_display }}</td>
                <td>{{ user.motDePasse }}</td>
                <td><a href="/compte/{{ user.id }}/delete">delete</a></td>
            </tr>
            {% endfor %}
        </table>

    </div>
</body>
</html>

gestion_vente/templates/compte_login.html
{% extends "layout.html" %}
{% block title %}
Se Connecter
{% endblock %}
{% block content %}
<div class="compte_creer w">
    <fieldset>
        <legend>Connectez-vous</legend>
        <form method="post" novalidate>
            {% csrf_token %}
            <div >
                <label >Nom du compte / Téléphone / Courriel</label><br>
                 <input type="text" name ="data_login"><br>
                 <label >Mot de passe</label><br>
                 <input type="password" name="pwd" id=""><br>
                 <span style="color: red;">{{ msg_error}}</span>
               </div>
               <!-- <div class="form-group">
                <label for="id_code">图片验证码</label>
                <div class="row">
                    <div class="col-xs-7">
                        {{ form.code }}
                        <span style="color: red;">{{ form.code.errors.0 }}</span>
                    </div>
                    <div class="col-xs-5">
                        <img id="image_code" src="/image/code/" style="width: 125px;">
                    </div>
                </div>
            </div> -->
              <button type="submit" class="btn">continuer</button>
          </form>
    </fieldset>
    <div class="compte_creer"><h2><a href="/compte/creer/">Créer un compte</a></h2></div>

</div>
{% endblock %}

</body>
</html>

gestion_vente/templates/home1.html
{% extends "layout.html" %}
{% block title %}
Amazonneuve
{% endblock %}
{% block content %}
<link rel="stylesheet" href="/static/css/home.css">

<div class="w" >
    <div class="img_roulant_container">
        <ul>
            <li>
                <a href="/compte/shopping/?type=fruit_legume"><img  src="/static/imgs/legume.jpg"></a>
            </li>
            <li>
                <a href="/compte/shopping/?type=viande"><img  src="/static/imgs/viande.jpg"></a>
            </li>
            <li>
                <a href="/compte/shopping/?type=laitier_et_oeufs"><img  src="/static/imgs/milk.jpg"></a>
            </li>
            <li>
                <a href="/compte/shopping/?type=pain"><img  src="/static/imgs/boulangerie.jpg"></a>
            </li>
            <li>
                <a href="/compte/shopping/?type=surgeles"><img  src="/static/imgs/surgele.jpg"></a>
            </li>
            <li>
                <a href="/recette/?r=0"><img  src="/static/imgs/recette.jpg"></a>
            </li>
        </ul>
        <a href="javascript:;" class="arrow_l">&lt;</a>
        <a href="javascript:;" class="arrow_r">&gt;</a>
        <ol class="circle"></ol>
    </div>
</div>
<script src="/static/js/home.js"></script>
{% endblock %}

gestion_vente/templates/inventaire_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventaire Edit</title>
</head>
<body>
   
        <h1>Inventaire Éditer</h1>
        
        <div >
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                <div >
                   <label for="">{{field.label}}</label>
                    {{field}}
                    <span style="color: red;">{{field.errors.0}}</span>
                  </div>
                  {% endfor %} 
                  <button type="submit" >confirmer</button>
              </form>
        </div>
      
</body>
</html>

gestion_vente/templates/inventaire_liste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventaire Liste</title>
</head>
<body>
    <h1>Inventaire Liste</h1>
    <table>
        <thead>
            <th>ID</th>
            <th>Produit</th>
            <th>Quantite en stock</th>
            <th>Date péremption</th>
            <th>Numéro de lot</th>
            <th>Modifier</th>
        </thead>
        <tbody>
            {% for obj in liste %}
            <tr>
                <td>{{ obj.id }}</td>
                <td>{{ obj.idProduit }}</td>
                <td>{{ obj.inventaire }}</td>
                <td>{{ obj.dateLimite }}</td>
                <td>{{ obj.numLot }}</td>
                <td>
                    <a href="/inventaire/{{ obj.id }}/delete/">delete</a>
                    <a href="/inventaire/{{ obj.id }}/edit/">edit</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

gestion_vente/templates/liste_panier.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>liste panier</title>
</head>
<body>
    <table>
        <thead>
            <th>id</th>
            <th>nom compte</th>
            <th>produit</th>
            <th>qty</th>
        </thead>
        <tbody>
            {% for obj in liste %}
            <tr>
                <td>{{obj.id}}</td>
                <td>{{obj.nomCompte}}</td>
                <td>{{obj.idProduit}}</td>
                <td>{{obj.quantite}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

gestion_vente/templates/produit_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Produit Edite</title>
</head>
<body>
   
        <h1>Produit Edite</h1>
        
        <div >
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                <div >
                   <label for="">{{field.label}}</label>
                    {{field}}
                    <span style="color: red;">{{field.errors.0}}</span>
                  </div>
                  {% endfor %} 
                  <button type="submit" >Confirmer</button>
              </form>
        </div>
      
</body>
</html>